server:
  port: 8099
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: 'http://localhost:4200'
            allowedMethods: '*'
            allowedHeaders: '*'
    config:
      fail-fast: true
      uri: http://localhost:8888/
      import: optional:configserver:http://localhost:8888/
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
