### DATABASE ###
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/evaluation?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
  security:
    enabled: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: evaluation
# Spring Cloud Config
 # cloud:
  #  config:
   #   fail-fast: true
   #   uri: http://localhost:8888/
   #   import: http://localhost:8888
  #config:
 #   import: optional:configserver:http://localhost:8888



### JPA / HIBERNATE ###
server:
  port: 8088

# Eureka registration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
